### ISSUE TITLE
ch05/04-correct/correct.js 내 callback 함수 호출 부재

### ISSUE THREAD

**Issue by hun-a** [Jpub/JSWebCrawler#1]
안녕하세요. [자바스크립트와 Node.js를 이용한 웹 크롤링 테크닉](http://jpub.tistory.com/651) 책을 잘 보고 있습니다. 😄 

ch05/04-correct/correct.js 파일 내 4번째 라인에서 `var Mecab = require('./mecab-mod-sync.js');` 하는 부분의 모듈 명이 책에서 만든 `mecab-mod.js`와는 다르네요.
그리고  25번째 라인에서 `mecab.parse()` 호출시 콜백함수 인자 없이 호출하고 있는데요... 혹시 다른 모듈로 작성하셨나 궁금합니다.

확인을 부탁드립니다.

**Comment by Jpub** [comment]
확실히 본문과 소스코드에는 mecab-mod-sync.js로 들어가 있군요.
원서와 원서코드에는 mecab-mod.js로 되어 있어서 역자 님을 통해서 확인 중입니다. 
답변이 오면 말씀드리도록 하겠습니다. 즐거운 주말 보내세요!

**Comment by Jpub** [comment]
5장 4절에서는 이전에 작성했던 mecab-mod.js대신에 mecab-mod-sync.js를 사용하는데, 
책과 깃허브에 mecab-mod.js를 사용하는 걸로 잘못 설명이 들어갔습니다..

mecab-mod-sync.js는 mecab-mod.js와 달리 마지막에 callback(res);가 아닌 return res;를 합니다. 

그렇게 되면, 순서를 지켜서 함수를 호출하는 프로그램을 작성할 때 콜백방식보다 용이하게 사용할 수 있습니다. 

테스트하실 때는 일단 mecab-mod.js 를 복사하여 mecab-mod-sync.js를 만드시고, 그 안에서 callback(res);를 return res;로 바꿔서 
돌려보시면 되겠습니다. 
 
혼돈을 드려 죄송합니다. 
 
이 동 규 드림 

============================================================

소스코드 역시 수정된 내용으로 업데이트 하였습니다. 감사합니다!

**Comment by hun-a** [comment]
답변 감사드립니다 ^^
